### PR TITLE
Rewrite the build process in Grunt 0.4.5, use jQuery & QUnit from npm

### PR DESCRIPTION
**Pull request by mgol**
Also, update the QUnit syntax to the new API not relying on globals.

cc @gnarf

### CODE REVIEW

**Comment by mgol** [comment]
@gnarf ping

**Comment by gnarf** [comment]
LGTM!

**Comment by mgol** [comment]
@gnarf Can I tag `0.2.0`? Changing all `-pre` references to that version & tagging it is enough, isn't it? Is this package published somewhere or does it only have tags in the repo and that's it?

**Comment by gnarf** [comment]
yeah - it hadn't been published anywhere I don't think

**Comment by gnarf** [comment]
Release Notes in README, and feel free to publish to npm (just remember to add me to the publishers ;))

**Comment by mgol** [comment]
To publish to npm we'll need to change the name in `package.json` - uppercase letters have not been allowed for new packages for some time.

**Comment by gnarf** [comment]
yeah - we should do that anyway...

Since it hadn't been published, I don't think I see any problems with this

**Comment by mgol** [comment]
The package is on npm: https://www.npmjs.com/package/jquery.requestanimationframe

I made some mistakes in updating the README & version updates (leaving `-pre` & old versions here & there) so I released 0.2.1 & 0.2.2 after 0.2.0 (oops). It'd be good to automate that part one day.

I added you as a co-owner.

I also switched from JSHint to ESLint to follow what jQuery Core did.

**Comment by gnarf** [comment]
😘 thanks so much for updating all of this @mgol !

**Pull request closed without merging**
