### PR TITLE
Browserify support

### PR DESCRIPTION
**Pull request by jantimon**
this adds support for:

+ browserify
+ webpack
+ requireJs

from: https://github.com/umdjs/umd/blob/master/jqueryPlugin.js

### CODE REVIEW

**Comment by jeffchan** [comment]
:+1: @gnarf Any way to get this merged? Would love to use this with webpack

**Comment by arturparkhisenko** [comment]
:+1:

**Comment by jeffchan** [comment]
@gnarf Thanks! Can we also get a new version published on NPM? Happy to make the PR but would need you to publish

**Comment by gnarf** [comment]
Yeah - I'll give you collab to make it easier... will you be able to publish if you have collab?

**Pull request merged**
